- name: Make selinux permissive
  selinux:
    policy: targeted
    state: permissive
  when: ansible_os_family == "RedHat"

- name: install firewalld package
  yum:
    name: firewalld
    state: present

- name: Make sure firewall is stopped
  systemd: state=stopped enabled=no name=firewalld
  when: ansible_os_family == "RedHat"
