---
- hosts: localhost
  gather_facts: yes
  vars_files:
    - vars/external_vars.yml

  vars_prompt:
  - name: "sonar_username"
    prompt: "Enter Sonar username"
    private: no
  - name: "sonar_password"
    prompt: "Enter Sonar password"
    private: yes

  tasks:
  - name: create conf file
    file:
      path: '{{ configuration_file }}'
      state: touch

  - name: clean file
    shell: echo > '{{ configuration_file }}'

  - name: get sonar version
    include_tasks: server_version.yml

  - name: get installed plugins list
    include_tasks: installed_plugin.yml

  - name: get projects list
    include_tasks: projects.yml

  - name: get groups list
    include_tasks: groups.yml

  - name: get users list
    include_tasks: users.yml
